"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "@/components/headers/index";
import {useRef, useEffect} from 'react'
// import FluidSimulation from 'fluid-simulation-react';

// import ReactFluidAnimation from '@usertive/react-fluid-animation';


// import Fluid from 'webgl-fluid'
// import FluidAnimation from 'react-fluid-animation'

// import Footer from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "KGM Group",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const canvas = useRef(null)
  // useEffect(function () {
  //   let c = canvas.current
  //   Fluid(c)
  // }, [])
  const customConfig = {
    textureDownsample: 2,
    densityDissipation: 0.80,
  };
   const customColors = [
    [1, 1, 0], // Yellow
    [0, 1, 1]  // Cyan
  ]

  return (
    <html lang="en">
     {/* <FluidAnimation
      /> */}

      <body className={inter.className}>

      {/* <canvas ref={canvas}></canvas> */}
      {/* <div className="WeglFluid">
      <FluidSimulation  color={customColors}/>
      </div> */}
        <Headers />
        {/* <ReactFluidAnimation /> */}

        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
